name: Close stale issues

on:
  schedule:
    - cron: "30 2 * * *"

permissions:
  issues: write

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v10
        with:
          # === 核心参数 ===
          days-before-issue-stale: 30
          days-before-issue-close: 14

          stale-issue-message: |
            This issue has been automatically marked as stale because it has been open 30 days with no activity.
            It will be closed in this run. Reopen if still relevant.

          close-issue-message: |
            Closed due to no activity for 30 days.

          days-before-pr-stale: -1
          days-before-pr-close: -1

          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-label: "stale"
          remove-stale-when-updated: true
          exempt-issue-labels: "bug,enhancement,good first issue,help wanted,blocked"
          ascending: true
